/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Grass.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GrassModel(props) {
  const { nodes, materials } = useGLTF('/Grass.glb')
  return (
    <group {...props} dispose={null} scale={[1.5,1.5,1.5]} position={[0,-5,0]}>
      <mesh geometry={nodes.Grass.geometry} material={materials.grass} position={[0, 0, -0.544]} scale={8.005} />
      <mesh geometry={nodes.Grass10.geometry} material={materials.grass} position={[-134.296, 65.811, -16.832]} rotation={[0, 0.399, 0]} scale={0.086} />
    </group>
  )
}

useGLTF.preload('/Grass.glb')
