/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 newGrass.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NewGrassModel(props) {
  const { nodes, materials } = useGLTF('/newGrass.glb')
  return (
    <group {...props} dispose={null}  scale={[1.5,1.5,1.5]}  position={[-5,-3,0]}>
      <group position={[0.003, 0.189, 0.042]} scale={8.672}>
        <mesh geometry={nodes.sc_grass_clump_03_high011.geometry} material={materials['Sc Grass 01']} />
        <mesh geometry={nodes.sc_grass_clump_03_high011_1.geometry} material={materials['Sc type D']} />
        <mesh geometry={nodes.sc_grass_clump_03_high011_2.geometry} material={materials['Sc type D dead']} />
      </group>
    </group>
  )
}

useGLTF.preload('/newGrass.glb')
