/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 potato.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export  function SortingObjectModel({props,sortingobject}) {
  console.log(`sorting object : ${sortingobject}`);
  const { nodes, materials } = useGLTF(`/${sortingobject}.glb`)
  console.log(materials);
  if(sortingobject==='potato'){
    return (
      <group {...props} dispose={null} position={[0,0,0]} scale={[0.4,0.4,0.4]}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Potato.001']} />
    </group>
    )

  }

  
useGLTF.preload(`/${sortingobject}.glb`)

}

