/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WoovenBasket.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export  function VeggieBasketModel(props) {
  const { nodes, materials } = useGLTF('/WoovenBasket.glb')
  return (
    <group {...props} dispose={null}  scale={[0.1,0.1,0.1]} position={[0.8,0.2,0]}>
   
      <mesh geometry={nodes.Celtic.geometry} material={materials.wooden} />
    </group>
  )
}

useGLTF.preload('/WoovenBasket.glb')
