/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Potato.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Potato.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Potato.001']} />
    </group>
  )
}

useGLTF.preload('/Potato.glb')
