/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Rat.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Rat.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RatArmature001" position={[-5.931, 0.227, -13.333]} rotation={[2.999, 1.512, -2.992]} scale={0.395}>
          <primitive object={nodes.root} />
          <primitive object={nodes.neutral_bone} />
          <skinnedMesh name="mouse002" geometry={nodes.mouse002.geometry} material={materials['Material_0.001']} skeleton={nodes.mouse002.skeleton} />
        </group>
        <group name="NurbsPath" position={[-4.304, 0, -12.672]} rotation={[-Math.PI, 0.775, -Math.PI]} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[-5.506, -1.211, 16.872]} scale={[4.279, 6.762, 4.279]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-5.506, -1.211, -12.663]} scale={[4.279, 6.762, 4.279]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Procedural cheese.001']} position={[13.332, 0.479, 1.345]} rotation={[Math.PI, -0.439, Math.PI]} scale={0.467} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Procedural cheese.001']} position={[11.856, 0.444, 2.32]} rotation={[Math.PI, -0.439, Math.PI]} scale={0.467} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.floor} position={[-0.3, -0.614, 2.036]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-28.157, -0.573, -21.193]} />
        <group name="Cube001" position={[-5.098, 5.587, 2.036]} scale={[1, 6.339, 20.352]}>
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Wall} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.Wall} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Procedural cheese']} position={[11.856, 0.444, 0.247]} scale={0.467} />
      </group>
    </group>
  )
}

useGLTF.preload('/Rat.glb')
